In [1]:
from scipy.stats import t
from scipy.linalg import pinvh as inv
from numpy.linalg import lstsq
import numpy.matlib as mb
import ipywidgets as widgets
import math as mt
import numpy as np
import pandas as pd
import re   

# Calibração

In [2]:
def MMQ(y, mx):
  coef = (inv(mx.T @ mx)) @ (mx.T @ y) # Faz a linearização com os dados
  return (coef)

In [4]:
def RMSE(yReal, yEstimado): # root-mean-square deviation
  residuos = np.sum(np.power((yReal - yEstimado),2))**0.5
  return(residuos)

In [7]:
def calcular_r2(y_true, y_pred):
    """
    Calcula o coeficiente de determinação R².
    
    Parâmetros:
    y_true: array-like, Valores observados (reais).
    y_pred: array-like, Valores preditos pelo modelo.
    
    Retorno:
    r2: float, Coeficiente de determinação R².
    """
    # Converter para arrays do NumPy, caso não sejam
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    # Média dos valores observados
    y_mean = np.mean(y_true)
    
    # Soma dos quadrados dos resíduos (SSR)
    ss_res = np.sum((y_true - y_pred) ** 2)
    
    # Soma total dos quadrados (SST)
    ss_tot = np.sum((y_true - y_mean) ** 2)
    
    # Cálculo de R²
    r2 = 1 - (ss_res / ss_tot)
    
    return r2

## Caso 1: Sistema de 1º Ordem sendo avaliado por diversas ordens

In [8]:
x = np.matrix(np.arange(0,10,1)+np.random.uniform(0,1,10))
y = np.matrix((56*x+32)+(np.random.uniform(0,1,10)))

In [7]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[55.99943849]] [[32.43062493]]
[[ 72.74929145 143.93331154 148.04003844 201.41325779 287.06042949
  331.06678746 409.84059158 468.44610692 521.56227224 550.71980018]] 
 [[ 72.62048914 143.96242582 148.25642218 201.69992545 286.64616316
  330.7443595  410.17156798 468.58853404 521.05140136 551.09059846]]
0.974846444775614
0.9999963521242358


In [8]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-0.00619969]] [[56.06261517]] [[32.32121698]]
[[ 72.74929145 143.93331154 148.04003844 201.41325779 287.06042949
  331.06678746 409.84059158 468.44610692 521.56227224 550.71980018]] 
 [[ 72.55322876 143.95425191 148.25116254 201.72483671 286.69578903
  330.79556521 410.20622248 468.59509597 521.02123377 551.03450072]]
0.9667992553967878
0.999996412100833


In [9]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-0.00397141]] [[0.05358328]] [[55.81515724]] [[32.56450819]]
[[ 72.74929145 143.93331154 148.04003844 201.41325779 287.06042949
  331.06678746 409.84059158 468.44610692 521.56227224 550.71980018]] 
 [[ 72.64824786 143.91045735 148.20323939 201.6566763  286.67619347
  330.81677619 410.28156368 468.6612201  521.01862671 550.95888604]]
0.948791215620589
0.9999965445156924


## Caso 2: Sistema de 2º Ordem sendo avaliado por diversas ordens

In [10]:
x = np.matrix(np.arange(0,10,1)+np.random.uniform(0,1,10))
y = np.matrix((56*np.power(x,2)+30*x+32)+(np.random.uniform(0,1,10)))

In [11]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[606.02124037]] [[-959.15785632]]
[[  79.48803211  126.29537903  534.13229665 1006.17857889 1406.81112419
  2099.55944309 2404.21066187 3422.77174002 4605.56062466 5844.43420679]] 
 [[-543.06436605 -320.38361779  699.76640205 1410.79263027 1884.53839483
  2563.637324   2825.51664445 3596.86600933 4357.07496757 5054.69769863]]
1454.327626924471
0.9381915505875313


In [12]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[55.98227618]] [[30.17919821]] [[32.26162607]]
[[  79.48803211  126.29537903  534.13229665 1006.17857889 1406.81112419
  2099.55944309 2404.21066187 3422.77174002 4605.56062466 5844.43420679]] 
 [[  79.37368108  126.26891784  534.37039556 1006.43956935 1406.52883726
  2099.38159557 2404.1273732  3423.22217978 4605.07516973 5844.65436792]]
0.8624787034632647
0.9999999782619742


In [13]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-0.0044488]] [[56.05240156]] [[29.88414273]] [[32.51673051]]
[[  79.48803211  126.29537903  534.13229665 1006.17857889 1406.81112419
  2099.55944309 2404.21066187 3422.77174002 4605.56062466 5844.43420679]] 
 [[  79.45781917  126.28572065  534.25203451 1006.34719016 1406.48383659
  2099.41728183 2404.19122608 3423.33218158 4605.13513429 5844.53966241]]
0.8232468944348953
0.9999999801946035


## Caso 3: Pontos de um arquivo sendo avaliado por diversas ordens

In [14]:
input = np.asmatrix(np.loadtxt('dados/dadosexp.txt', dtype='f', delimiter=','))
print(input[:,0].T,input[:,1].T)
x = input[:,0].T
y = input[:,1].T

[[ 800.9   909.2   989.15 1083.45 1195.55 1299.25 1348.6  1409.55 1493.3 ]] [[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]]


In [15]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[0.03008989]] [[-19.80499247]]
[[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]] 
 [[ 4.29399943  7.55273392  9.95842082 12.79589504 16.1689744  19.2892943
  20.77422953 22.6082104  25.12823851]]
0.6117922901583075
0.9990934798974811


In [16]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[1.51579282e-05]] [[-0.00521078]] [[-9.28100936e-06]]
[[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]] 
 [[ 5.54959262  7.79257144  9.67653479 12.14771517 15.43607513 18.8172347
  20.54079022 22.7713846  26.02008075]]
1.9525722318499654
0.9907661320957912


In [17]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[3.33800336e-09]] [[6.72008657e-06]] [[1.15577957e-08]] [[1.52574693e-11]]
[[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]] 
 [[ 6.02537988  8.06392877  9.80558969 12.13382706 15.30943974 18.6647682
  20.4091994  22.69990076 26.10091541]]
2.4206691426861875
0.9858081076567031
