In [3]:
from scipy.stats import t
from scipy.linalg import pinvh as inv
from numpy.linalg import lstsq
import numpy.matlib as mb
import ipywidgets as widgets
import math as mt
import numpy as np
import pandas as pd
import re   

# Calibração

In [4]:
def MMQ(y, mx):
  coef = (inv(mx.T @ mx)) @ (mx.T @ y) # Faz a linearização com os dados
  return (coef)

In [5]:
def RMSE(yReal, yEstimado): # root-mean-square deviation
  residuos = np.sum(np.power((yReal - yEstimado),2))**0.5
  return(residuos)

In [6]:
def calcular_r2(y_true, y_pred):
    """
    Calcula o coeficiente de determinação R².
    
    Parâmetros:
    y_true: array-like, Valores observados (reais).
    y_pred: array-like, Valores preditos pelo modelo.
    
    Retorno:
    r2: float, Coeficiente de determinação R².
    """
    # Converter para arrays do NumPy, caso não sejam
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    # Média dos valores observados
    y_mean = np.mean(y_true)
    
    # Soma dos quadrados dos resíduos (SSR)
    ss_res = np.sum((y_true - y_pred) ** 2)
    
    # Soma total dos quadrados (SST)
    ss_tot = np.sum((y_true - y_mean) ** 2)
    
    # Cálculo de R²
    r2 = 1 - (ss_res / ss_tot)
    
    return r2

## Caso 1: Sistema de 1º Ordem sendo avaliado por diversas ordens

In [7]:
x = np.matrix(np.arange(0,10,1)+np.random.uniform(0,1,10))
y = np.matrix((56*x+32)+(np.random.uniform(0,1,10)))

In [8]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[55.97169201]] [[32.61799819]]
[[ 75.38649828 121.43575665 190.17648213 205.38739732 273.03796184
  348.33189328 376.06150192 472.59057889 505.2038226  542.85264208]] 
 [[ 75.22904342 121.53783911 190.55479703 205.37835581 273.05484282
  347.84648745 376.19541232 471.98997353 505.4942006  543.18358292]]
0.9933884404947684
0.9999959197119949


In [9]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-0.01087683]] [[56.08107199]] [[32.42700938]]
[[ 75.38649828 121.43575665 190.17648213 205.38739732 273.03796184
  348.33189328 376.06150192 472.59057889 505.2038226  542.85264208]] 
 [[ 75.11502128 121.49316631 190.58584572 205.42135315 273.13300672
  347.92652072 376.26600261 471.98736621 505.45095195 543.08530034]]
0.9695238384703823
0.9999961134022194


In [10]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-0.01421842]] [[0.19838778]] [[55.23779923]] [[33.22807515]]
[[ 75.38649828 121.43575665 190.17648213 205.38739732 273.03796184
  348.33189328 376.06150192 472.59057889 505.2038226  542.85264208]] 
 [[ 75.38911697 121.42570056 190.35417569 205.19514491 273.04611565
  348.07598339 376.48716184 472.18619916 505.4902131  542.81472372]]
0.7499113212989936
0.9999976747351063


## Caso 2: Sistema de 2º Ordem sendo avaliado por diversas ordens

In [11]:
x = np.matrix(np.arange(0,10,1)+np.random.uniform(0,1,10))
y = np.matrix((56*np.power(x,2)+30*x+32)+(np.random.uniform(0,1,10)))

In [12]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[598.9539385]] [[-932.56767119]]
[[ 115.62125113  195.33100251  323.31680588  751.18445962 1105.07681449
  2202.73471701 2950.1194435  3683.76014057 4394.32654059 5243.91383166]] 
 [[-347.85867611  -60.11496533  281.71853477 1058.28142089 1532.88074069
  2639.00778749 3233.29969059 3745.8187041  4195.35567043 4686.99609944]]
1087.7705280954701
0.9629319331115651


In [13]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[56.01513916]] [[29.85036833]] [[32.95877261]]
[[ 115.62125113  195.33100251  323.31680588  751.18445962 1105.07681449
  2202.73471701 2950.1194435  3683.76014057 4394.32654059 5243.91383166]] 
 [[ 115.48161149  195.29050418  323.70511689  751.04176452 1104.92714352
  2202.72278271 2950.32657383 3683.6353205  4394.35784676 5243.89634255]]
0.5240223928960767
0.9999999913974926


In [14]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-9.00868345e-05]] [[56.01653764]] [[29.8443026]] [[32.96509656]]
[[ 115.62125113  195.33100251  323.31680588  751.18445962 1105.07681449
  2202.73471701 2950.1194435  3683.76014057 4394.32654059 5243.91383166]] 
 [[ 115.48326293  195.29068146  323.70414081  751.04006918 1104.92591168
  2202.72356218 2950.32805055 3683.63665702 4394.35821278 5243.89445837]]
0.524006781062303
0.9999999913980052


## Caso 3: Pontos de um arquivo sendo avaliado por diversas ordens

In [16]:
input = np.asmatrix(np.loadtxt('dados/dadosexp.txt', dtype='f', delimiter=','))
print(input[:,0].T,input[:,1].T)
x = input[:,0].T
y = input[:,1].T

[[ 946.55 1103.55 1217.75 1359.95 1428.15 1464.85 1572.75 1664.4  1706.65]] [[5.43 6.09 6.7  7.39 7.72 7.9  8.47 8.94 9.11]]


In [17]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[0.00492273]] [[0.71001823]]
[[5.43 6.09 6.7  7.39 7.72 7.9  8.47 8.94 9.11]] 
 [[5.36962631 6.1424949  6.70467019 7.40468186 7.74041227 7.92107615
  8.45223861 8.90340675 9.111392  ]]
0.09568360986539284
0.9992809831485815


In [18]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-3.84085744e-07]] [[0.00598254]] [[9.08706024e-06]]
[[5.43 6.09 6.7  7.39 7.72 7.9  8.47 8.94 9.11]] 
 [[5.31866082 6.13429634 6.71568426 7.42561543 7.76059192 7.93937142
  8.45900117 8.8933489  9.09140725]]
0.14735590760474537
0.9982947067652316


In [19]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-3.10640846e-09]] [[8.34489228e-06]] [[1.22161854e-08]] [[1.37071511e-11]]
[[5.43 6.09 6.7  7.39 7.72 7.9  8.47 8.94 9.11]] 
 [[4.84222966 5.98782284 6.76516802 7.62042245 7.97179163 8.14213666
  8.55671571 8.79434524 8.86421833]]
0.7902075026526435
0.950960474056767
